{% set name = "tcfile" %}
{% set version = "2024.10.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 1a2e63e46ca97c6390a69e212eeee3392b08491f2319e44608ce5d6f8fd39085

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - flit-core
    - pip
    - python >=3.7,<4.0
  run:
    - h5py >=3.2.0,<4
    - hdf5plugin >=4.4,<5
    - numpy >=1.18.5,<2
    - pillow >=9.5.0,<10
    - python >=3.7,<4.0
    - dask

test:
  imports:
    - TCFile
  commands:
    - pip list
    - pip check
  requires:
    - pip

about:
  home: https://github.com/ehgus/TCFile
  summary: Python package for handling TCF data. It works with Tomcube data
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ehgus
    - goanpeca
