{% set name = "tcfile" %}
{% set version = "2024.11.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 6fd4ed5b25e2f482bb53a1beee5744742292f2c29229b316d9e995b96f4f6878

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - flit-core
    - pip
    - python >=3.7,<4.0
  run:
    - h5py >=3.2.0,<4
    - hdf5plugin >=4.4,<5
    - numpy >=1.18.5,<2
    - pillow >=9.5.0,<10
    - python >=3.7,<4.0
    - dask

test:
  imports:
    - TCFile
  commands:
    - pip list
    - pip check
  requires:
    - pip

about:
  home: https://github.com/ehgus/TCFile
  summary: Python package for handling TCF data. It works with Tomcube data
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ehgus
    - goanpeca
