{% set name = "tcfile" %}
{% set version = "2023.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: ed3073f798e37fd001fb3af0fda8137179bb5d26748dc4297b0db008a0601988

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - flit-core
    - pip
    - python >=3.7,<4.0
  run:
    - h5py >=3.2.0,<4
    - numpy >=1.18.5,<2
    - pillow >=9.5.0,<10
    - python >=3.7,<4.0

test:
  imports:
    - TCFile
  commands:
    - pip list
    - pip check
  requires:
    - pip

about:
  home: https://github.com/ehgus/TCFile
  summary: Python package for handling TCF data. It works with Tomcube data
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ehgus
    - goanpeca
